### ISSUE TITLE
Activity status

### ISSUE THREAD

**Issue by matuskosut** [mathworks/jupyter-matlab-proxy#10]
Hi,

We noticed that Desktop application currently shows activity status in bottom left corner. Do you plan to show these in Matlab online?

![matlab_ready](https://user-images.githubusercontent.com/10776269/120166526-f3bb7480-c1fc-11eb-85c6-1d0bbf585c3e.png)

I got feedback from users, that it is a little bit hard then to know if the script is actually running (e.g. longer times between log messages) when not showing busy. Or to know if they can run another script now.

![matlab_busy](https://user-images.githubusercontent.com/10776269/120167040-8f4ce500-c1fd-11eb-9300-4f81a2fbc4ee.png)

**Comment by prabhakk-mw** [comment]
Thank you @matuskosut.

Your feedback will be relayed our development organization, who will consider this feature in a future release of the product.

I'll reach out to you, once this feature is available.
