### ISSUE TITLE
Getting unsupported operand type error for executing cells

### ISSUE THREAD

**Issue by kekeke21** [mathworks/jupyter-matlab-proxy#100]
### Summary

Running any script on jupyter notebook cell returns this error. My local matlab works just fine. 
`unsupported operand type(s) for +: 'NoneType' and 'str'
`

### Browser(s) used

Chrome

### Issue found in

MATLAB Kernel

### Script output

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                                                                                                    MATLAB
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

matlab - C:\Program Files\MATLAB\R2023b\bin\matlab.EXE ok

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                                                                                               matlab-proxy-app
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

matlab-proxy-app - C:\Users\kento\AppData\Roaming\Python\Python312\Scripts\matlab-proxy-app.EXE ok

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                                                                                                   Jupyter
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

jupyter - C:\Users\kento\AppData\Roaming\Python\Python312\Scripts\jupyter.EXE ok

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                                                                                          Python and pip executables
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

python - C:\Python312\python.EXE ok

Python 3.12.4

pip - C:\Python312\Scripts\pip.EXE ok

pip 24.2 from C:\Users\kento\AppData\Roaming\Python\Python312\site-packages\pip (python 3.12)

python3 - None  X
Recommendation: python3 is not installed. Please install python3.

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                                                                                                OS information
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Windows
11
Windows-11-10.0.22631-SP0
uname_result(system='Windows', node='KentThinkpadX1', release='11', version='10.0.22631', machine='AMD64')

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                                                                                              Conda information
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

conda - C:\Users\kento\miniconda3\condabin\conda.BAT

conda 24.5.0

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                                                                                              Installed packages
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

jupyter_client            8.6.1
jupyter-console           6.6.3
jupyter_core              5.7.2
jupyter-events            0.10.0
jupyter-lsp               2.2.5
jupyter-matlab-proxy      0.15.2
jupyter_server            2.14.2
jupyter_server_proxy      4.4.0
jupyter_server_terminals  0.5.3
jupyterlab                4.2.5
jupyterlab_pygments       0.3.0
jupyterlab_server         2.27.3
matlab-proxy              0.23.1
notebook                  7.2.2
notebook_shim             0.2.4

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                                                                                          Jupyter server extensions
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Config dir: C:\Users\kento\.jupyter

Config dir: C:\Python312\etc\jupyter

Config dir: C:\ProgramData\jupyter

`sys_prefix` level settings are read-only, using `user` level for migration to `lockedExtensions`
JupyterLab v4.2.5
C:\Users\kento\AppData\Roaming\Python\share\jupyter\labextensions
        jupyterlab_pygments v0.3.0 enabled ok (python, jupyterlab_pygments)
        jupyter_matlab_labextension v1.0.0 enabled ok (python, jupyter_matlab_labextension)
        @jupyter-notebook/lab-extension v7.2.2 enabled ok
        @jupyterhub/jupyter-server-proxy v4.4.0 enabled ok

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                                                                                            Environment variables
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by kekeke21** [comment]
I believe it is the same as #98 which closed without a solution

**Comment by kekeke21** [comment]
Worked after removing password config from `.jupyter`
https://github.com/mathworks/jupyter-matlab-proxy/issues/23#issuecomment-1525033545

**Comment by prabhakk-mw** [comment]
@kekeke21 Thank you for reporting this issue.

[jupyter-matlab-proxy version 0.15.3](https://github.com/mathworks/jupyter-matlab-proxy/releases/tag/jupyter-matlab-proxy-v0.15.3) fixes this issue, such that the appropriate error message should now be displayed, warning you of the password being set in the Jupyter Notebook Server.

Please let us know if this is not the case for you after you upgrade to v0.15.3

To upgrade to the latest version please run the following command in the appropriate python virtual environment.
```bash
python -m pip install -U jupyter-matlab-proxy 
```

Thank you!
