### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by jankap** [mathworks/jupyter-matlab-proxy#12]
Dear all,

is a similar proxy planned for Windows, too? Would be great to have some notebook support in VSCode (I like the live scripts' functionality but they are terrible to be used in version control & online code review. Jupyter Notebooks can be rendered very often though.

Thanks

**Comment by prabhakk-mw** [comment]
@jankap 

Thank you for reaching out to us, and your valuable feedback.
I will forward your request for Windows support to the Development organisation. 

Could you please elaborate more on what your request for "notebook support in VSCode" ?
Are you referring to Jupyter notebooks? or [VScode Notebooks](https://code.visualstudio.com/blogs/2021/08/05/notebooks)? 
Are you only interested in using Notebooks through VSCode?

**Comment by rashedmyt** [comment]
Duplicate of #35

**Comment by prabhakk-mw** [comment]
Dear @jankap 

As of v0.6.0 of `jupyter-matlab-proxy`, the package should now support Windows. 
Please let us know if you face any issues with using it.
