### ISSUE TITLE
how to get back to the state before

### ISSUE THREAD

**Issue by xllowl** [mathworks/jupyter-matlab-proxy#15]
after python -m pip install .
I can not start my lab server.

error:

'ExtensionManager' object has no attribute '_extensions'

**Comment by prabhakk-mw** [comment]
Try

1. python -m pip show jupyter-matlab-proxy
if nothing shows that means the install didn’t go through
2. Then uninstall using 
python -m pip uninstall jupyter-matlab-proxy

Also when you’re installing try to install using PyPI
 using 

python -m pip install jupyter-matlab-proxy 
Do this from your home folder.

**Comment by xllowl** [comment]
i solved that problem by downgrade the jupyter server

pip install jupyter_server==1.6..4
