### ISSUE TITLE
Please make it clear that this only works if you have MATLAB for cloud use already set up.

### ISSUE THREAD

**Issue by harleyday** [mathworks/jupyter-matlab-proxy#16]
Hi,

I went through each of the required steps for installation listed in your README without any errors. I was confused as to why MATLAB wasn't appearing in jupyterhub or jupyterlab interfaces. I *think* the reason may be down to the licence we're using not extending as far as cloud use. Does this sound about right?

If my suspicion is correct, please add this information to your README as I only worked this out after extensively searching the MATLAB website - it really wasn't obvious. Adding this will likely safe others some time.

Best wishes,
Harley

**Comment by diningPhilosopher64** [comment]
Hi @harleyday,

Thank you for trying the MATLAB Jupyter integration.

As a first step, ensure the appropriate packages are installed in the same environment from where you are launching
the jupyter lab/ notebook 
```bash
$ pip freeze | grep -E "jupyter|matlab-proxy|jupyter-matlab-proxy"
``` 
The output should contain the entries `jupyter-matlab-proxy` and `matlab-proxy`.

Next, execute the below command:
```bash
$ jupyter serverextension list
```

Verify that you are able to see similar output: 
```bash
config dir: /path/to/my/python/virtualenv/etc/jupyter
    jupyter_server_proxy  enabled 
    - Validating...
      jupyter_server_proxy  OK
    jupyterlab  enabled 
    - Validating...
      jupyterlab 3.3.2 OK
```

Next run the below command:
```bash
jupyter nbextension list
```

Verify that you are able to see similar output as below:
```bash
Known nbextensions:
  config dir: /path/to/my/python/virtualenv/etc/jupyter/nbconfig
    tree section
      jupyter_server_proxy/tree  enabled 
      - Validating: **OK**
```

If the server does not show up, then install `jupyter_contrib_nbextensions`:
```bash
$ pip install jupyter_contrib_nbextensions
```

Now relaunch jupyter lab/notebook and see if the MATLAB option is visible.



If none of the above work, try creating a new virtualenv and install jupyter-matlab-proxy in it:

```bash
#Create a virtualenv and activate it
$ python3 -m venv .venv
$ source .venv/bin/activate

# Install jupyter-matlab-proxy and jupyter lab
(.venv) $ pip install jupyter-matlab-proxy
(.venv) $ pip install jupyterlab

# Launch jupyter lab
(.venv) $ jupyter lab
```

**Comment by prabhakk-mw** [comment]
@harleyday ,
Please re-open this issue if the troubleshooting steps outlined by @diningPhilosopher64 do not solve the issue.

To reiterate, the symptoms you've described do not indicate a MATLAB licensing issue.
It sounds more like an Python/Jupyter environment issue.

**Comment by prabhakk-mw** [comment]
Hi @harleyday please feel free to [email me](mailto:prabhakk@mathworks.com) if this is still an issue for you.
