### ISSUE TITLE
Stuck in Online License Manager

### ISSUE THREAD

**Issue by rocthered** [mathworks/jupyter-matlab-proxy#17]
Hi,

I was triyng to use the jupyter-matlab. After clicking Matlab in the jupyter lab, I got stuck in this:
<img width="722" alt="Screen Shot 2022-04-28 at 2 42 45 PM" src="https://user-images.githubusercontent.com/11326220/165824421-20065f73-1411-47b7-a096-f907ad196798.png">
It seem to be in this stage forever.

I am using python 3.7 and matlab R2021b. 

I tried both MAC os and Ubuntu. Similar problem for both OS.

What can I do?

Thanks,

Dapeng

**Comment by diningPhilosopher64** [comment]
Hi @rocthered ,

Thank you for trying the MATLAB Jupyter integration.

This maybe related to write permissions.  We'll need the debug logs generated to help resolve the issue. For this, set the environment variable `MWI_LOG_LEVEL` to `DEBUG` and then launch jupyter lab process.

```bash
$ env MWI_LOG_LEVEL="DEBUG" jupyter lab
```

The `jupyter-matlab-proxy` depends on the [`matlab-proxy`](https://github.com/mathworks/matlab-proxy) package. 

The environment variable `MWI_LOG_LEVEL` influences the verbosity of logs generated by the `matlab-proxy` package.

For more information on the environment variables that can be set, refer [Advanced Usage.md](https://github.com/mathworks/matlab-proxy/blob/main/Advanced-Usage.md) file.

**Comment by rocthered** [comment]
Hi @diningPhilosopher64,

Thank you so much for the timely reply!

Somehow it works now in the linux system, probably after I intalled xvfb (not 100% sure if that is the reason)! 

Anyway thank you for your help!

**Comment by belafdil-chakib** [comment]
Hello, 

I have the exact same issue but it did not resolve as the author.

I put the env MWI_LOG_LEVEL="DEBUG" prefix and here is the output:

```
env MWI_LOG_LEVEL="DEBUG" jupyter lab
[...]

[W 2023-03-01 17:15:32.254 LabApp] Could not determine jupyterlab build status without nodejs
DEBUG:MATLABProxyApp:inside decorator_authenticate_access
DEBUG:MATLABProxyApp:inside decorator_authenticate_access
DEBUG:MATLABProxyApp:Environment variable MWI_CUSTOM_HTTP_HEADERS is not set, hence no custom HTTP headers are applied.
DEBUG:MATLABProxyApp:Successfully validated provided jupyter configuration
DEBUG:MATLABProxyApp:DDUX value for matlab-proxy "MATLAB_PROXY:JUPYTER:V1"
DEBUG:MATLABProxyApp:Combined DDUX value to be used for MATLAB process: "MATLAB_PROXY:JUPYTER:V1"
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:MATLABProxyApp:Using MWI_APP_PORT to launch the server
DEBUG:MATLABProxyApp:Starting MATLAB proxy app
DEBUG:MATLABProxyApp: with base_url: /matlab and app_port:47003.
DEBUG:MATLABProxyApp:Server info stored into: /home/xxxx/.matlab/MWI/ports/47003/mwi_server.info
INFO:MATLABProxyApp:
======================================================================================================================================================
                                                              MATLAB can be accessed at:
                                                            http://127.0.0.1:47003/matlab
======================================================================================================================================================
DEBUG:MATLABProxyApp:Registering handler for signal: 1
DEBUG:MATLABProxyApp:Registering handler for signal: 2
DEBUG:MATLABProxyApp:Registering handler for signal: 3
DEBUG:MATLABProxyApp:Registering handler for signal: 15
DEBUG:MATLABProxyApp: inside authenticate_access for request:<Request GET /matlab/ >
DEBUG:MATLABProxyApp: inside authenticate_request for request:<Request GET /matlab/ >
DEBUG:MATLABProxyApp: Token Authentication is NOT Enabled!!
DEBUG:MATLABProxyApp: Request is authenticated, proceed to endpoint:<function root_redirect at 0x7f4944a8c8b0><Request GET /matlab/ >
[I 2023-03-01 17:15:37.428 ServerApp] 302 GET /matlab/ (ccd02b71c10241d983aa6a7a3a4c37cf@127.0.0.1) 661.63ms
DEBUG:MATLABProxyApp: inside authenticate_request for request:<Request GET /matlab/authenticate_request >
DEBUG:MATLABProxyApp: Token Authentication is NOT Enabled!!
DEBUG:MATLABProxyApp:!!!!!! REQUEST IS AUTHORIZED !!!!
[W 2023-03-01 17:15:54.125 ServerApp] 400 PUT /matlab/set_licensing_info (ccd02b71c10241d983aa6a7a3a4c37cf@127.0.0.1) 23.31ms referer=http://127.0.0.1:9996/matlab/index.html

```

**Comment by diningPhilosopher64** [comment]
Hello @belafdil-chakib ,

Thank you for trying the MATLAB Jupyter integration.

Can you share more information about your environment:

* The OS in which jupyter lab is being launched from.

* The python version being used:
  ```bash
  $ python --version
  ```

* Versions of `jupyter`, `matlab-proxy` and `jupyter-matlab-proxy` installed in the environment:
  ```bash
  $ pip freeze | grep -E "jupyter|matlab-proxy|jupyter-matlab-proxy"
  ```

* Confirm if `xvfb` is installed:
  ```bash
  $ which xvfb
  ```
