### ISSUE TITLE
Promblem about the location and extension

### ISSUE THREAD

**Issue by Naturezju** [mathworks/jupyter-matlab-proxy#18]
Hi, here I encountered 2 problems what should I do?

problem 1:
$which matlab
zsh: command not found: matlab

p2:   notebook section
      nbextensions_configurator/config_menu/main  enabled 
      - Validating: problems found:
        - require?  X nbextensions_configurator/config_menu/main
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
    tree section
      jupyter_server_proxy/tree  enabled 
      - Validating: OK
      nbextensions_configurator/tree_tab/main  enabled 
      - Validating: problems found:
        - require?  X nbextensions_configurator/tree_tab/main

Looking forward to your reply~

**Comment by Naturezju** [comment]
the jupyter serverextension list is all OK

**Comment by Naturezju** [comment]
However, the jupyter serverextension list is all OK and the result check written as:
(jmatlab) yezhixiao@yezhixiaodeMacBook-Pro jupyter-matlab-proxy % python -m matlab_kernel.check
Matlab kernel v0.17.1
Metakernel v0.29.2
Python v3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:01:00) 
[Clang 13.0.1 ]
Python path: /Users/yezhixiao/miniforge3/envs/jmatlab/bin/python

Connecting to Matlab...
Matlab connection established
Matlab Kernel

        Matlab engine not installed:
        See https://www.mathworks.com/help/matlab/matlab-engine-for-python.htm

**Comment by prabhakk-mw** [comment]
@Naturezju 
**Error 1:**
```
which matlab
zsh: command not found: matlab
```
Please install MATLAB and add it to your system PATH to resolve this.

Also it seems like you are using a MacBook.
The `jupyter-matlab-proxy` package does not support macOS yet.

**Error 2:**
```
    Matlab engine not installed:
    See https://www.mathworks.com/help/matlab/matlab-engine-for-python.htm
```
To resolve this issue, you need to install the `matlab-engine-for-python`. The link in the error message should give more information about how to install the engine.

**Comment by prabhakk-mw** [comment]
@Naturezju 
`matlab-proxy v0.5.0` has just been released with support for MacOS.

It should now be possible to launch MATLAB on MacOS through this Jupyter integration as well.

To upgrade your existing environment, execute the following command :
```
python3 -m pip install --upgrade matlab-proxy
```
