### ISSUE TITLE
How to pass additional startup commands to MATLAB through matlab-proxy-app?

### ISSUE THREAD

**Issue by TidbitSoftware** [mathworks/jupyter-matlab-proxy#20]
Normally when calling `matlab` from the command line on my local machine, I will use the `-r` option with `addpath` commands to set up paths to directories containing custom MATLAB modules. I would do something similar for the MATLAB launcher in JupyterLab (installed on top of TLJH). I know how to do this for notebook kernel launchers. Is there something similar to `kernel.json` for the MATLAB launcher (specifically, that would allow me to modify the call to the `matlab` binary so that the `-r` option is passed)?

Edit: Also, I'm wondering if it is possible to move the launcher from 'Notebook' to 'Other'?

**Comment by TidbitSoftware** [comment]
I found what I was looking for in `/opt/tljh/user/lib/python3.9/site-packages/jupyter_matlab_proxy/__init__.py`.

I still would like to know about re-categorizing the launcher from 'Notebook' to 'Other' if anyone knows how to do this.

**Comment by prabhakk-mw** [comment]
Dear @TidbitSoftware 

Thank you for the question. I think this is an interesting usecase for which we would like to design a supported solution. There isn't a trivial way to accomplish this at the moment. 

I'm reopening this issue until a solution has been created for this.

**Comment by prabhakk-mw** [comment]
@TidbitSoftware 
To answer your other question " Ability to move launcher to Other from Notebook"

Unfortunately, this is controlled by the `jupyter-server-proxy` extension that we use to enable this capability and is outside of our control.

This PR (jupyterhub/jupyter-server-proxy#244), on the `jupyter-server-proxy` repository enables the ability to configure the location of the launcher icons. If and when it gets merged in, future versions of their package should enable this capability.

**Comment by rsp34** [comment]
Not sure how many different projects you work across but could you try setting your start-up folder as discussed in https://uk.mathworks.com/help/matlab/matlab_env/matlab-startup-folder.html and putting a startup.m in that folder?

**Comment by prabhakk-mw** [comment]
@TidbitSoftware 
v0.18.0 of matlab-proxy has been released with support to provide a startup script  to matlab-proxy-app.

See [Run Custom MATLAB Startup Code](https://github.com/mathworks/matlab-proxy/blob/main/Advanced-Usage.md#run-custom-matlab-startup-code)

Thank you!
