### ISSUE TITLE
Cannot use jupyter matlab in Windows

### ISSUE THREAD

**Issue by zguo235** [mathworks/jupyter-matlab-proxy#21]
OS: Windows 11 22H2
Python: 3.10.9 (Microsoft store)
> pip list
Package                           Version
--------------------------------- -----------
aiohttp                           3.8.3
aiohttp-session                   2.12.0
aiosignal                         1.3.1
anyio                             3.6.2
argon2-cffi                       21.3.0
argon2-cffi-bindings              21.2.0
arrow                             1.2.3
asttokens                         2.2.1
async-timeout                     4.0.2
attrs                             22.2.0
Babel                             2.11.0
backcall                          0.2.0
beautifulsoup4                    4.11.2
bleach                            6.0.0
certifi                           2022.12.7
cffi                              1.15.1
charset-normalizer                2.1.1
colorama                          0.4.6
comm                              0.1.2
cryptography                      39.0.0
debugpy                           1.6.6
decorator                         5.1.1
defusedxml                        0.7.1
executing                         1.2.0
fastjsonschema                    2.16.2
fqdn                              1.5.1
frozenlist                        1.3.3
idna                              3.4
ipykernel                         6.20.2
ipython                           8.9.0
ipython-genutils                  0.2.0
isoduration                       20.11.0
jedi                              0.18.2
Jinja2                            3.1.2
json5                             0.9.11
jsonpointer                       2.3
jsonschema                        4.17.3
jupyter_client                    8.0.2
jupyter-contrib-core              0.4.2
jupyter-contrib-nbextensions      0.7.0
jupyter_core                      5.2.0
jupyter-events                    0.6.3
jupyter-highlight-selected-word   0.2.0
jupyter-matlab-proxy              0.5.0
jupyter-nbextensions-configurator 0.6.1
jupyter_server                    2.2.0
jupyter-server-proxy              3.2.2
jupyter_server_terminals          0.4.4
jupyterlab                        3.5.3
jupyterlab-pygments               0.2.2
jupyterlab_server                 2.19.0
lxml                              4.9.2
MarkupSafe                        2.1.2
matlab-proxy                      0.5.6
matplotlib-inline                 0.1.6
mistune                           2.0.4
multidict                         6.0.4
nbclassic                         0.5.1
nbclient                          0.7.2
nbconvert                         7.2.9
nbformat                          5.7.3
nest-asyncio                      1.5.6
notebook                          6.5.2
notebook_shim                     0.2.2
packaging                         23.0
pandocfilters                     1.5.0
parso                             0.8.3
pickleshare                       0.7.5
pip                               23.0
platformdirs                      2.6.2
prometheus-client                 0.16.0
prompt-toolkit                    3.0.36
psutil                            5.9.4
pure-eval                         0.2.2
pycparser                         2.21
Pygments                          2.14.0
pyrsistent                        0.19.3
python-dateutil                   2.8.2
python-json-logger                2.0.4
pytz                              2022.7.1
pywin32                           305
pywinpty                          2.0.10
PyYAML                            6.0
pyzmq                             25.0.0
requests                          2.28.2
rfc3339-validator                 0.1.4
rfc3986-validator                 0.1.1
Send2Trash                        1.8.0
setuptools                        65.5.0
simpervisor                       0.4
six                               1.16.0
sniffio                           1.3.0
soupsieve                         2.3.2.post1
stack-data                        0.6.2
terminado                         0.17.1
tinycss2                          1.2.1
tomli                             2.0.1
tornado                           6.2
traitlets                         5.9.0
uri-template                      1.2.0
urllib3                           1.26.14
wcwidth                           0.2.6
webcolors                         1.12
webencodings                      0.5.1
websocket-client                  1.5.0
yarl                              1.8.2

Error:
<img width="581" alt="image" src="https://user-images.githubusercontent.com/33446677/216282454-fdb3296e-b6d6-481f-a29e-f57fde58b460.png">

Message in Terminal:
[I 2023-02-02 18:11:48.656 ServerApp] Creating new notebook in
[I 2023-02-02 18:11:48.890 ServerApp] Kernel started: 4f21fb7f-58c3-406d-8691-546fa2c6797d
[I 2023-02-02 18:11:50.160 ServerApp] Connecting to kernel 4f21fb7f-58c3-406d-8691-546fa2c6797d.
[I 2023-02-02 18:11:50.245 ServerApp] Connecting to kernel 4f21fb7f-58c3-406d-8691-546fa2c6797d.
[I 2023-02-02 18:11:50.282 ServerApp] Connecting to kernel 4f21fb7f-58c3-406d-8691-546fa2c6797d.

**Comment by prabhakk-mw** [comment]
Hi @zguo235 
Thank you for trying the MATLAB Integration for Jupyter.

Unfortunately, the `jupyter-matlab-proxy` package does not currently have support for Windows as listed in the [Requirements](https://github.com/mathworks/jupyter-matlab-proxy#requirements) section of the README.

We are actively working on solutions to alleviate the situation.

In the mean time, Are you able to use WSL2 on your windows 11 machine to work around this limitation ?

**Comment by zguo235** [comment]
Thank you for the rapid response. jupyter-matlab-proxy works normally on wsl2!

**Comment by prabhakk-mw** [comment]
Dear @zguo235 

As of v0.6.0 of `jupyter-matlab-proxy`, the package should now support Windows. 
Please let us know if you face any issues with using it.
