### ISSUE TITLE
Clarification on documentation about MATLAB process/license sharing

### ISSUE THREAD

**Issue by TidbitSoftware** [mathworks/jupyter-matlab-proxy#26]
The documentation states,
> NOTE: All notebooks in a Jupyter server share the same underlying MATLAB process. Executing code in one notebook will effect the workspace in other notebooks. Users must be mindful of this while working with multiple notebooks at the same time.

On a multi-user system (for example, a JupyterLab/JupyterHub instance), is this all notebooks for a given user, or all notebooks for all users?

Likewise, on a multi-user system, if a user activates MATLAB with their license or checks out a license from a license server, it does not apply to other users on the same machine, right?

**Comment by prabhakk-mw** [comment]
On a multi-user system, each user is served on a separate notebook server by jupyter. All notebooks opened in this server by a given user, share the same MATLAB instance. 

There is no sharing of MATLAB processes or licensing between users even if they happen to be hosted on the same machine.

**Comment by TidbitSoftware** [comment]
Thank you!
