### ISSUE TITLE
Documentation request: How to integrate with Azure Machine Learning Compute custom apps

### ISSUE THREAD

**Issue by adriantorrie** [mathworks/jupyter-matlab-proxy#32]
# How do we use this in Azure ML Compute custom apps?

## Notes:

- Azure ML custom apps do NOT allow for command line switches to be passed in (e.g. as if a `docker run` command was being issued)
- Azure ML would probably need the [`mathworks/matlab202Xy`](https://hub.docker.com/r/mathworks/matlab) image installed first as a custom app?
- Or would the VM itself need MATLAB installed as part of a [compute setup script](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-customize-compute-instance?view=azureml-api-2#create-the-setup-script)? (We wouldn't want
- We use a network licence manager
  - Inputting usernames and passwords for proxy access into the custom app screen is a security risk (for the network licence manager authentication), and won't be allowed in our organisation as the env vars are shown in free text form once entered (screenshot below). 
- Is there a way to combine this into a single container using [`mathworks/matlab202Xy`](https://hub.docker.com/r/mathworks/matlab) as the base image (higher than 2022a so it has `matlab-proxy` aready in the container)?

![Azure ML env vars](https://github.com/mathworks/jupyter-matlab-proxy/assets/3909039/15b157d4-e1ac-4bff-be69-741e5d6b19d3)

**Comment by adriantorrie** [comment]
Azure ML custom apps do NOT allow for command line switches to be passed in (e.g. as if a docker run command was being issued)

**Comment by adriantorrie** [comment]
https://github.com/mathworks/jupyter-matlab-proxy/issues/34

**Comment by prabhakk-mw** [comment]
Hi @adriantorrie 

The Dockerfile listed in the previous comment would need to be built with your license server information with the LICENSE_SERVER build time argument.
```bash
docker build --build-arg LICENSE_SERVER=**27000@my-server**
             --build-arg BASE_IMAGE=mathworks/matlab:r2023a 
             -f Dockerfile -t my_image:r2023a .
```

Once built, this image will **NOT** require any run time arguments to launch the container directly in `matlab-proxy`

A sample docker run command is:
```
docker run -it --rm --init -p 8888:8888 my_image:r2023a
```

The `-it --rm --init` command line switches provided to the docker run command here are only best practices to ensure that the container launches and shuts down correctly, and `-p 8888:8888` is required to open the ports to communicate with the application from within the container.

_Uploading_ the image built from this Dockerfile into Azure ML should result in:
1. Not requiring to pass in the `MLM_LICENSE_FILE environment variable` to Azure ML.
2. The container launches directly into `matlab-proxy` interface, this avoids needing to pass in any additional flags at `docker run` stage.

Kindly help me understand what I've missed in my understanding of your requirements.

**Comment by prabhakk-mw** [comment]
Closing this issue, as I haven't heard back from you in a while. 
Kindly comment on this thread if you would like to continue this conversation.
