### ISSUE TITLE
Reopen: https://github.com/mathworks/jupyter-matlab-proxy/issues/32

### ISSUE THREAD

**Issue by adriantorrie** [mathworks/jupyter-matlab-proxy#34]
Reopen: https://github.com/mathworks/jupyter-matlab-proxy/issues/32

> Azure ML custom apps do NOT allow for command line switches to be passed in (e.g. as if a docker run command was being issued)

MW: Read the actual issue instead of regurgitating what is already known!

**Comment by prabhakk-mw** [comment]
Dear @adriantorrie 

I have reopened #32. 

Please consider explaining why the provided dockerfile does not satisfy your requirements.
