### ISSUE TITLE
can not login when "open MATLAB"

### ISSUE THREAD

**Issue by QibangLiu** [mathworks/jupyter-matlab-proxy#38]
Flowing the instruction, I got the error:
`
Error connecting to MATLAB. Check the status of MATLAB by clicking the "Open MATLAB" button. Retry after ensuring MATLAB is running successfully
`
![image](https://github.com/mathworks/jupyter-matlab-proxy/assets/62950134/65b19383-dd01-43b2-9cec-a1c5c02f7c59)

Then I clicked the Open MATLAB button, entered my email and password, and clicked the sign-in button, but nothing happened.  is there any clue to solve it? Thanks.

**Comment by krisctl** [comment]
Dear @QibangLiu ,

Thank you for trying out jupyter-matlab-proxy! It appears that your MathWorks account is not linked to a valid license. Can you check the terminal from where you launched Jupyter to see if an error is displayed there? It should be similar to "ERROR:MATLABProxyApp: Your MathWorks account is not linked to a valid license for MATLAB R20xxx". If that is the case, attaching a valid license with your account is required before proceeding forward. If this error isn't shown on the terminal, please enable debug mode by setting the environment variable MWI_LOG_LEVEL=DEBUG and starting Jupyter, and sharing the logs here.

**Comment by QibangLiu** [comment]
@krisctl  thanks for reply. I can run matlab from terminal very well ( see below figure). Please find the below logs. 

![image](https://github.com/mathworks/jupyter-matlab-proxy/assets/62950134/8099cdd9-8d8c-4b05-92e4-6e5af695ad8e)


`(fenics) [qibang@ssm-serv-02 repository]$ export MWI_LOG_LEVEL=DEBUG 
(fenics) [qibang@ssm-serv-02 repository]$ echo $MWI_LOG_LEVEL 
DEBUG
(fenics) [qibang@ssm-serv-02 repository]$ jupyter lab
[I 2023-06-20 22:44:58.689 ServerApp] Package jupyterlab took 0.0001s to import
[I 2023-06-20 22:44:58.752 ServerApp] Package jupyter_lsp took 0.0624s to import
[W 2023-06-20 22:44:58.752 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-06-20 22:44:58.911 ServerApp] Package jupyter_server_proxy took 0.1582s to import
[I 2023-06-20 22:44:58.933 ServerApp] Package jupyter_server_terminals took 0.0211s to import
[I 2023-06-20 22:44:58.937 ServerApp] Package nbclassic took 0.0034s to import
[W 2023-06-20 22:44:58.943 ServerApp] A `_jupyter_server_extension_points` function was not found in nbclassic. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-06-20 22:44:58.943 ServerApp] Package notebook_shim took 0.0000s to import
[W 2023-06-20 22:44:58.944 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-06-20 22:44:58.945 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2023-06-20 22:44:58.945 ServerApp] jupyter_server_proxy | extension was successfully linked.
[I 2023-06-20 22:44:58.953 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2023-06-20 22:44:58.960 ServerApp] jupyterlab | extension was successfully linked.
[I 2023-06-20 22:44:58.965 ServerApp] nbclassic | extension was successfully linked.
[I 2023-06-20 22:45:00.311 ServerApp] Package jupyter_nbextensions_configurator took 0.5478s to import
[W 2023-06-20 22:45:00.311 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_nbextensions_configurator. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-06-20 22:45:00.311 ServerApp] jupyter_nbextensions_configurator | extension was found and enabled by notebook_shim. Consider moving the extension to Jupyter Server's extension paths.
[I 2023-06-20 22:45:00.311 ServerApp] jupyter_nbextensions_configurator | extension was successfully linked.
[I 2023-06-20 22:45:00.312 ServerApp] notebook_shim | extension was successfully linked.
[I 2023-06-20 22:45:00.543 ServerApp] notebook_shim | extension was successfully loaded.
[I 2023-06-20 22:45:00.547 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2023-06-20 22:45:00.548 ServerApp] [jupyter_nbextensions_configurator] enabled 0.6.3
[I 2023-06-20 22:45:00.548 ServerApp] jupyter_nbextensions_configurator | extension was successfully loaded.
INFO:MATLABProxyApp:Initializing Jupyter MATLAB Proxy
DEBUG:MATLABProxyApp:Icon_path:  /home/qibang/mambaforge3/envs/fenics/lib/python3.8/site-packages/jupyter_matlab_proxy/icon_open_matlab.svg
DEBUG:MATLABProxyApp:Launch Command: matlab-proxy-app
DEBUG:MATLABProxyApp:Extension Name: Jupyter
[I 2023-06-20 22:45:00.625 ServerApp] jupyter_server_proxy | extension was successfully loaded.
[I 2023-06-20 22:45:00.627 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2023-06-20 22:45:00.645 LabApp] JupyterLab extension loaded from /home/qibang/mambaforge3/envs/fenics/lib/python3.8/site-packages/jupyterlab
[I 2023-06-20 22:45:00.645 LabApp] JupyterLab application directory is /home/qibang/mambaforge3/envs/fenics/share/jupyter/lab
[I 2023-06-20 22:45:00.647 LabApp] Extension Manager is 'pypi'.
[I 2023-06-20 22:45:00.655 ServerApp] jupyterlab | extension was successfully loaded.
[I 2023-06-20 22:45:00.672 ServerApp] nbclassic | extension was successfully loaded.
[I 2023-06-20 22:45:00.674 ServerApp] The port 8888 is already in use, trying another port.
[I 2023-06-20 22:45:00.674 ServerApp] The port 8889 is already in use, trying another port.
[I 2023-06-20 22:45:00.675 ServerApp] The port 8890 is already in use, trying another port.
[I 2023-06-20 22:45:00.676 ServerApp] The port 8891 is already in use, trying another port.
[I 2023-06-20 22:45:00.677 ServerApp] Serving notebooks from local directory: /home/qibang/repository
[I 2023-06-20 22:45:00.677 ServerApp] Jupyter Server 2.6.0 is running at:
[I 2023-06-20 22:45:00.677 ServerApp] http://localhost:8892/lab?token=84bfd8e4f080b31af18666ec2fb900f26c401b8fe259ffb8
[I 2023-06-20 22:45:00.677 ServerApp]     http://127.0.0.1:8892/lab?token=84bfd8e4f080b31af18666ec2fb900f26c401b8fe259ffb8
[I 2023-06-20 22:45:00.677 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2023-06-20 22:45:00.868 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/qibang/.local/share/jupyter/runtime/jpserver-232067-open.html
    Or copy and paste one of these URLs:
        http://localhost:8892/lab?token=84bfd8e4f080b31af18666ec2fb900f26c401b8fe259ffb8
        http://127.0.0.1:8892/lab?token=84bfd8e4f080b31af18666ec2fb900f26c401b8fe259ffb8
[I 2023-06-20 22:45:01.213 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[I 2023-06-20 22:45:20.580 ServerApp] 302 GET / (@127.0.0.1) 1.42ms
[W 2023-06-20 22:45:24.206 LabApp] Could not determine jupyterlab build status without nodejs
[I 2023-06-20 22:45:59.635 ServerApp] Kernel started: a061868e-30ee-45d6-8686-8601256a8585
[I 2023-06-20 22:46:02.332 ServerApp] 302 GET /matlab (921c9f35a4424918aab12c7592469c76@::1) 2.32ms
DEBUG:MATLABProxyApp:Environment variable MWI_CUSTOM_HTTP_HEADERS is not set, hence no custom HTTP headers are applied.
DEBUG:MATLABProxyApp:Successfully validated provided jupyter configuration
DEBUG:MATLABProxyApp:DDUX value for matlab-proxy "MATLAB_PROXY:JUPYTER:V1"
DEBUG:MATLABProxyApp:Combined DDUX value to be used for MATLAB process: "MATLAB_PROXY:JUPYTER:V1"
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:MATLABProxyApp:Using MWI_APP_PORT to launch the server
DEBUG:MATLABProxyApp:Starting MATLAB proxy app
DEBUG:MATLABProxyApp: with base_url: /matlab and app_port:49043.
DEBUG:MATLABProxyApp:Server info stored into: /home/qibang/.matlab/MWI/ports/49043/mwi_server.info
INFO:MATLABProxyApp:
======================================================================================================================================================
                                                              MATLAB can be accessed at:                                                              
                                                            http://127.0.0.1:49043/matlab                                                             
======================================================================================================================================================
DEBUG:MATLABProxyApp:Registering handler for signal: 1 
DEBUG:MATLABProxyApp:Registering handler for signal: 2 
DEBUG:MATLABProxyApp:Registering handler for signal: 3 
DEBUG:MATLABProxyApp:Registering handler for signal: 15 
[I 2023-06-20 22:46:04.945 ServerApp] 302 GET /matlab/ (921c9f35a4424918aab12c7592469c76@::1) 2610.62ms
[I 2023-06-20 22:46:04.987 ServerApp] Connecting to kernel a061868e-30ee-45d6-8686-8601256a8585.
[I 2023-06-20 22:46:05.132 ServerApp] Starting buffering for a061868e-30ee-45d6-8686-8601256a8585:a2ac421e-fbb0-4cd9-a5ff-8d7330fe433c
[I 2023-06-20 22:46:05.143 ServerApp] Connecting to kernel a061868e-30ee-45d6-8686-8601256a8585.
[IPKernelApp] WARNING | Unknown message type: 'comm_open'
[IPKernelApp] WARNING | Unknown message type: 'comm_msg'
[I 2023-06-20 22:46:05.280 ServerApp] Connecting to kernel a061868e-30ee-45d6-8686-8601256a8585.
[I 2023-06-20 22:46:07.190 ServerApp] 302 GET /matlab (b0d739e35d2747768f2507535b5b9603@127.0.0.1) 1.00ms
[I 2023-06-20 22:46:07.310 ServerApp] 302 GET /matlab/ (b0d739e35d2747768f2507535b5b9603@127.0.0.1) 6.35ms
DEBUG:MATLABProxyApp: inside authenticate_request for request:<Request GET /matlab/get_env_config >
DEBUG:MATLABProxyApp: Token Authentication is NOT Enabled!!
DEBUG:charset_normalizer:Encoding detection: utf_8 is most likely the one.
ERROR:MATLABProxyApp:Your MathWorks account is not linked to a valid license for MATLAB R2023a.
INFO:MATLABProxyApp:Resetting cached licensing information...
INFO:MATLABProxyApp:Deleting any cached licensing files!
[I 2023-06-20 22:47:25.668 ServerApp] Saving file at /Untitled.ipynb`

**Comment by prabhakk-mw** [comment]
@QibangLiu 

The following error message in the logs:

> ERROR:MATLABProxyApp:Your MathWorks account is not linked to a valid license for MATLAB R2023a.

tells me that the MATLAB account that was used to login does not have an associated license available for use from this environment.

There are 2 possible solutions:
1. Update `matlab-proxy` to version `0.7.0`. This version introduces the ability to use start MATLAB without providing licensing information to `matlab-proxy` *as long as MATLAB as already been activated on the local machine* . 
You could either set the environment variable `MWI_USE_EXISTING_LICENSE=True` and then launch your jupyter environment. Or if you prefer you could also use the newly introduced `Existing License` tab that is presented in the UI for the licensing screens.
Use the following commands to update `matlab-proxy`

      > conda activate fenics 
      python -m pip install --upgrade matlab-proxy
      
      and verify the version of  the installed packages by executing 
      
      > python -m pip list | grep matlab

2. Verify that the license that you are using is linked to the MathWorks Account that is being used to login to `matlab-proxy`.


I'd recommend using **option 1.** listed above. Please let us know if you need any more assistance and I'll be happy to re-open this issue!

**Comment by QibangLiu** [comment]
@prabhakk-mw The option 1 works. Thanks. However, I am running on a linux remote cluster, where I do not have the root access to install the Xvfb. I tried to install the Xvfb by conda [(),](https://anaconda.org/conda-forge/xorg-x11-server-xvfb-cos7-x86_64) but it does not work. Any suggestion to bypass this problem? Thanks.

![image](https://github.com/mathworks/jupyter-matlab-proxy/assets/62950134/0a6a9997-f91c-4641-aa6d-1d896e19f9b8)

**Comment by jhgoebbert** [comment]
Hi @QibangLiu ,
perhaps this suggestion helps: https://github.com/mathworks/matlab-proxy/issues/17
