### ISSUE TITLE
Support shortcut to un-comment a line

### ISSUE THREAD

**Issue by tylerlekang** [mathworks/jupyter-matlab-proxy#42]
**System:**
Windows 10
Matlab 2023a
Python 3.8.16 (via Miniconda)
Jupyter Lab 3.6.3 (via conda install)

**ISSUE:**
Using `Ctrl+/` works fine to comment lines of code (insert `% ` in front of code lines), but when I keep pressing this shortcut it does not *remove* the comment, and instead just continuously keeps adding them.

**Attempts to resolve:**
I looked in the advanced/JSON keyboard shortcut editor, but there aren't even any listed for commenting code lines. (I'm wondering if this means some of the shortcuts are more integral to the program and thus not editable?)

**Comment by tylerlekang** [comment]
**Note:** I realized this could be an issue with Jupyter Lab (on Windows), but on my same machine when using Notebooks with Python (in VS Code) there is no issue with the uncommenting.

**Comment by philipc-mw** [comment]
Thank you for trying out the MATLAB Integration for Jupyter, and thank you for the detailed issue report!

Unfortunately this line uncommenting shortcut is not a feature we currently support in this environment. I've reported this usecase to the development teams, and we will consider making this enhancement in a future version of the product. Thank you!

**Comment by prabhakk-mw** [comment]
Hi @tylerlekang 

Support for the `Ctrl+/` shortcut to comment/uncomment a line has been introduced in [v0.13.0 of jupyter-matlab-proxy](https://pypi.org/project/jupyter-matlab-proxy/0.13.0/).

I am marking this issue as closed, kindly do let us know if `v0.13.0` works as expected for you as well.

Thanks!
