### ISSUE TITLE
timeout too short for xvfb

### ISSUE THREAD

**Issue by shukti02** [mathworks/jupyter-matlab-proxy#46]
The timeout 100ms is too short for XVFB and quite often matlab doesn't start due to a timeout error.

**Comment by diningPhilosopher64** [comment]
Hi @shukti02 ,

Thank you for trying out the `jupyter-matlab-proxy` package.

The timeout registered by `jupyter-matlab-proxy` with `jupyter-server-proxy` is 100 seconds. As listed in [__init__.py](https://github.com/mathworks/jupyter-matlab-proxy/blob/main/src/jupyter_matlab_proxy/__init__.py#L51)

The value 100 corresponds to 100 seconds and not 100ms, as described in timeout field from the [jupyter-server-proxy documentation](https://jupyter-server-proxy.readthedocs.io/en/latest/server-process.html#timeout).

I suspect that there might be some other issue at play here.

Would you please share your answers to the following:




1. Does MATLAB launch successfully outside of `jupyter-matlab-proxy` ?

2. How long does MATLAB take to launch?

3. Could you please share the logs from executing the following command on your terminal, and clicking on the link to launch MATLAB:

```bash

env MWI_LOG_LEVEL=DEBUG matlab-proxy-app

```

4. Which form of licensing have you selected? (Online licensing, Network License Manager, Existing License)

5. Which version of MATLAB are you using?

6. What is the OS you are working with?


Thanks.

**Comment by shukti02** [comment]
Hi Sourabh,

Thanks for your quick response. Unfortunately we were unable to replicate
the problem and things work fine now.

We have installed the jupyter-matlab-proxy on our kubernates compute
cluster which runs jupyterhub. The OS for each virtual server is ubuntu.

Yes matlab launches successfully outside of the proxy (for example using
VNC which we have also integrated in our jupyterhub). The MATLAB version is
R2023a and licensing is online.

The problem only occurred for a few days post installation, wherein
everytime a new server was spawned and MATLAB had to be started for the
first time, it got stuck at 'starting MATLAB, this may take several
minutes' and after several minutes it showed 'failed to start due to a
timeout'. On inspecting the kubernates logs it showed something like
'shutting down xvfb' (not sure of the exact wording as I do not get this
error anymore). During that time we only managed to successfully start
MATLAB after several failed attempts. This gave the impression that it
would only start if everything loaded fast enough and if for
whatever reason the communication was slow, MATLAB would fail to start.

Since our system involves communication over the network at several stages,
there might be significant delays in loading individual modules.

Therefore, in my opinion, it might still be useful to increase timeouts
wherever there are any, to avoid this kind of problems in future.

Thanks a lot for your continued support.

One last question, is it planned to make the MATLAB Engine for Python
compatible with Python 3.11+  anytime in the near future?

Thanks and regards,

Shukti

**Comment by prabhakk-mw** [comment]
@shukti02, the MATLAB Engine for Python is maintained by another team at [matlab-engine-for-python](https://github.com/mathworks/matlab-engine-for-python)

There does already seem to be an open issue  
mathworks/matlab-engine-for-python/issues/33 on that repository which asks the same question, perhaps you could follow that thread to get an answer when the team provides one.

I'm closing this issue, but please feel free to create another issue when you need any more assistance!
Thank you!
