### ISSUE TITLE
pwd does not match current path in File Browser

### ISSUE THREAD

**Issue by TidbitSoftware** [mathworks/jupyter-matlab-proxy#49]
When I run `pwd` from inside a notebook with the kernel set to 'MATLAB kernel', the result is the user's home directory rather than the current location selected in the File Browser. Other kernels honor the currently-selected directory in the File Browser as the working directory. Is this not true of this kernel?

**Comment by rashedmyt** [comment]
Hi @TidbitSoftware,

Thank you for trying out MATLAB Integration for Jupyter.

As shown in the [architecture of MATLAB Kernel](https://github.com/mathworks/jupyter-matlab-proxy/tree/main/src/jupyter_matlab_kernel#architecture), all Notebooks using MATLAB Kernel use a single MATLAB instance. This MATLAB is started by Jupyter Server and hence the working directory of MATLAB is same as the directory from which Jupyter Server is started.

Hope this clarifies your query.

**Comment by TidbitSoftware** [comment]
Gotcha! Thanks for pointing this out @rashedmyt.
