### ISSUE TITLE
MATLAB Kernel Error: Invalid parameter name 'regionArray'. The name must be one of the following:

### ISSUE THREAD

**Issue by moxi000** [mathworks/jupyter-matlab-proxy#50]
MATLAB Kernel Error: 无效的参数名称 'regionArray'。 名称必须为以下项之一:
    'editorId'
    'requestId'
    'type'
    'startLine'
    'endLine'
    'fullText'
    'fullFilePath'
    'sectionBoundaries'
    'shouldResetState'
    'shouldDoFullCleanup'
    'customExecutionData'
    'partialEval'
    'documentStateToken'

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[I 2023-08-01 18:16:11.823 ServerApp] 302 GET /matlab (035d108ec1494590b2d063e9591dee3b@::1) 0.44ms
[I 2023-08-01 18:16:11.826 ServerApp] 302 GET /matlab/ (035d108ec1494590b2d063e9591dee3b@::1) 1.74ms
[IPKernelApp] WARNING | Unknown message type: 'comm_open'
[IPKernelApp] WARNING | Unknown message type: 'comm_msg'

**Comment by rashedmyt** [comment]
Hi @moxi000,

Thank you for trying out MATLAB Integration for Jupyter.

Can you confirm if the version of MATLAB used is R2023b Pre-release?

**Comment by moxi000** [comment]
Hi @rashedmyt ,  
Sure , I'm pretty sure I'm using R2023b preview, is this version confirmed to be incompatible? This version supports Apple's M-series processors for the first time, and the iteration performance is much better than the X64 version, so I can't wait to use this preview.
Thank you very much for your prompt reply.
