### ISSUE TITLE
The invalid path when saving the figure in web-mode

### ISSUE THREAD

**Issue by wjcper2008** [mathworks/jupyter-matlab-proxy#52]
Hi, someone also gets the same issus?
OS: centos7

Open matlab --> peaks --> save the figure --> The value of 'destination' is invalid. 

Warning: The value of 'destination' is invalid. Cannot create output file '/untitled2.png'.

![image](https://github.com/mathworks/jupyter-matlab-proxy/assets/14107030/bcccad80-ef61-4232-92eb-e688c541f006)

**Comment by krisctl** [comment]
Thanks for trying out jupyter-matlab-proxy, @wjcper2008 

To help me further diagnose this issue, can you clarify whether this behavior is observed only in the web-proxy mode or is it reproducible on the installed desktop MATLAB as well? Also, please share any logs written on the terminal from where the integration is launched. Please make sure to set `MWI_LOG_LEVEL=DEBUG` environment variable as instructed [here](https://github.com/mathworks/matlab-proxy/blob/main/Advanced-Usage.md) before starting the integration to collect more comprehensive logs.

As for the environment, kindly share the version of MATLAB where you are seeing this issue. Also, if you can provide any concrete steps to reproduce the issue, it will immensely help me out with issue reproduction at my end. Thanks!

**Comment by prabhakk-mw** [comment]
Closing the issue as we haven't heard back from @wjcper2008 
@wjcper2008 please feel free to add a comment with the information requested by @krisctl to re-open this issue.

Thank you!
