### ISSUE TITLE
MATLAB signin hangs after uninstalling a MATLAB version

### ISSUE THREAD

**Issue by asfilion** [mathworks/jupyter-matlab-proxy#53]
I had both R2023a and R2023b Prerelease installed on my Windows 11 machine. I tried installing both jupyterlab and this proxy via pip. Install worked fine and I was able to use Python notebooks.

When trying to use a MATLAB notebook I was asked to log into my MathWorks account. I did so and got an error saying my R2023b installation was not associated with a license. I'm guessing it grabbed the Prerelease since, as the most recent installation, it was at the top of the path. I believe Prerelease licensing may work different than normal release? My normal MATLABs are definitely associated with a license.

In any case, I wanted to use R2023a, so I tried editing my path variable to put R2023a on top in hopes it would pick up that version instead. However, after restarting jupyterlab, it was still trying to connect to R2023b. I then tried uninstalling R2023b, and now the attempt to sign into MATLAB hangs. 

I then tried uninstalling and reinstalling jupyterlab and the proxy with pip, and I still get the same hanging behavior. 

I'm guessing the proxy is writing information to some kind of config file that didn't get removed when uninstalled. In any case, I'm stuck and unable to use the proxy. Any suggestions?

**Comment by asfilion** [comment]
I tried launching from PowerShell this morning, and noticed that it is finding 23a. However as soon as I open a MATLAB notebook, before I run anything or try to log in, it starts infinitely repeating the same exception and permission error. See attached.
[jupyterlab_traceback.txt](https://github.com/mathworks/jupyter-matlab-proxy/files/12360095/jupyterlab_traceback.txt)

**Comment by krisctl** [comment]
Thanks @asfilion for trying jupyter-matlab-proxy!

1. There is a known issue with our ability to use Online Licensing for Pre-release versions of MATLAB, and the concerned development teams are looking into it as we speak.

To work around this issue one could attempt to use the "Existing License" tab on the licensing screen by:

    a. Launching MATLAB R2023b directly on your Windows Machine, and follow the screens to activate MATLAB.
    b. Once you are able to start additional MATLAB pre-release instances outside of the Jupyter environment without needing to pass any more licensing information you can:
        i. Start your Jupyter server from a terminal with the appropriate PATH to the version of MATLAB you would like to use
        ii. Select the "Existing License" tab from the licensing screen when shown.

2. Finally, we do cache some licensing information into `<user-home-dir>\.matlab\MWI\proxy_app_config.json`, which you can delete manually to start from a clean slate with respect to licensing. This should address the issue that you are seeing with our proxy not able to cleanup the config file.

**Comment by asfilion** [comment]
@krisctl Thanks for the reply. I had to delete the proxy_app_config.json file to get the login window to appear again. After that I was able to use "Existing License" tab and now it works as expected with 23a. I uninstalled the Prerelease as part of debugging this and don't have any more use for it, so I won't be trying that.
