### ISSUE TITLE
Use a shared matlab engine

### ISSUE THREAD

**Issue by rsp34** [mathworks/jupyter-matlab-proxy#59]
Enable the use of a shared engine as per https://uk.mathworks.com/help/matlab/ref/matlab.engine.shareengine.html

**Comment by prabhakk-mw** [comment]
Hi @rsp34 

It is already possible to use the `matlab.engine.shareEngine` through a jupyter notebook as long as:

1. The MATLAB Engine for Python is installed in the same python environment as `juptyer-matlab-proxy`.
2. One starts MATLAB through the kernel, and uses the MATLAB launched by the kernel from `python` through the MATLAB Engine for Python APIs.

Please refer to this [Dockerfile from the mathworks-ref-arch/matlab-integration-for-jupyter](https://github.com/mathworks-ref-arch/matlab-integration-for-jupyter/blob/main/matlab/Dockerfile) as a reference to the installation steps required to install `juptyer-matlab-proxy` & `matlabengineforpython`

Shown below are the steps I took from a container built using the Dockerfile listed above to showcase this:

1. Open a Terminal inside Jupyter to verify that the `matlabengineforpython`  is installed:

![image](https://github.com/mathworks/jupyter-matlab-proxy/assets/64955767/86a61bd0-8aa8-4b75-b2cf-104b657102a6)

2. Open a note book using the MATLAB Kernel option:

![image](https://github.com/mathworks/jupyter-matlab-proxy/assets/64955767/13c27ade-6696-47a8-986b-01d2b4d25cf5)

3. Execute the command `matlab.engine.shareEngine` inside this notebook. You might be asked to provide your license information if this is the first time you are running the integration.
**note: `matlab.engine.shareEngine` does not have any outputs on successful execution**

![image](https://github.com/mathworks/jupyter-matlab-proxy/assets/64955767/f5f07209-3716-4311-ba76-b06cd1375fe6)

4. Open a notebook using the `Python 3 (ipykernel)` as shown below:

![image](https://github.com/mathworks/jupyter-matlab-proxy/assets/64955767/fe246eaf-471f-4faf-9298-0562b390c3a8)

5. Execute the command `matlab.engine.connect_matlab` to connect to the previously shared engine. See [here ](https://in.mathworks.com/help/matlab/apiref/matlab.engine.connect_matlab.html)for more information on this command.

![image](https://github.com/mathworks/jupyter-matlab-proxy/assets/64955767/c298ecc9-4f5f-4302-b81f-7c870e103b34)

I hope this helpr, please let us know if you need any more information.

Thank you!

**Comment by rsp34** [comment]
Thanks for the detailed instructions! 👍

**Comment by prabhakk-mw** [comment]
You are right, the steps I've detailed here will not accomplish what you are looking for.
The steps above are to enable usage of the MATLAB spawned through the kernel with the MATLAB Engine for Python, which can then be used from Python notebooks.

Your last comment gives me much more clarity as to what you are looking for.
If you don't mind, could you please open another issue with a detailed description of your usecase ?

I ask this, as the capability you are looking for is not achievable out of the box, and would require us to either build such a feature in, or, provide you with some scripts/code changes which might enable that.
Having another issue to track that request would make it much easier for us to track.

Thank you!

**Comment by prabhakk-mw** [comment]
@rsp34 , I've created #64 to continue this thread. Please feel free to add any more information you'd like to provide into #64 

Thank you!

**Comment by rsp34** [comment]
Thanks @prabhakk-mw!
