### ISSUE TITLE
Switched to a trial license and now back to my original license

### ISSUE THREAD

**Issue by rsp34** [mathworks/jupyter-matlab-proxy#61]
I can't seem to use the MATLAB + Jupyter after switching.

![image](https://github.com/mathworks/jupyter-matlab-proxy/assets/8612468/32fe658d-51d7-4b48-a95f-145a24d80ce9)

**Comment by prabhakk-mw** [comment]
Can you please share screen shots of steps you took to get here?
Did you use online licensing?

Please try after deleting the folder: 
```bash
$HOME/.matlab/MWI
```

**Comment by rsp34** [comment]
Ahh, I needed to sign out and sign back in with the online license manager, and it worked fine. Sorry to bother you!

**Comment by prabhakk-mw** [comment]
Am glad to hear that you are unblocked!
Thank you for trying out `jupyter-matlab-proxy`!

**Comment by rsp34** [comment]
Thanks for the swift support. I'm glad to see all the work Mathworks is doing on integrating Jupyter and VS Code.
