### ISSUE TITLE
jupyter-matlab-kernel fails with JupyterHub

### ISSUE THREAD

**Issue by jhgoebbert** [mathworks/jupyter-matlab-proxy#62]
Hello,

I found that `jupyter-matlab-kernel` currently expects that `matlab-proxy` can be triggered on the node which runs the `jupyter-server+jupyter-server-proxy` by calling
```
url = "{protocol}://localhost:{port}{base_url}matlab
```
https://github.com/mathworks/jupyter-matlab-proxy/blob/main/src/jupyter_matlab_kernel/kernel.py#L153

But when running a multi-user-setup through a JupyterHub this port is NOT guaranteed to be accessible locally as it can be (ssh-)forwarded from a purly internal node to a system running the (configurable-)http-proxy.
Examples:
- https://github.com/NERSC/sshspawner
- https://github.com/FZJ-JSC/jupyter-jsc-jupyterhub/tree/main/custom/4.0.0/spawner

Hence, what you try to do here:
https://github.com/mathworks/jupyter-matlab-proxy/blob/v0.7.1/src/jupyter_matlab_kernel/kernel.py#L186
```
resp = requests.get(url, headers=headers, verify=False)
```
must fail in these situations and is unfortunately therefore no general solution.

Trying to access this port directly from the system running the `jupyter-server+jupyter-server-proxy` will be rejected as JupyterLab can only be accessed from outside by the browser through the (configurable-)http-proxy.

**Comment by jhgoebbert** [comment]
My current patch is
```
diff -Naur 0.7.1.orig/GCCcore-11.3.0-2023.3.6/jupytermatlabproxy/jupyter-matlab-proxy-0.7.1/src/jupyter_matlab_kernel/kernel.py 0.7.1/GCCcore-11.3.0-2023.3.6/jupytermatlabproxy/jupyter-matlab-proxy-0.7.1/src/jupyter_matlab_kernel/kernel.py
--- 0.7.1.orig/GCCcore-11.3.0-2023.3.6/jupytermatlabproxy/jupyter-matlab-proxy-0.7.1/src/jupyter_matlab_kernel/kernel.py        2023-08-21 14:27:12.000000000 +0200
+++ 0.7.1/GCCcore-11.3.0-2023.3.6/jupytermatlabproxy/jupyter-matlab-proxy-0.7.1/src/jupyter_matlab_kernel/kernel.py     2023-09-04 18:34:00.513906020 +0200
@@ -155,6 +155,16 @@
         port=nb_server["port"],
         base_url=nb_server["base_url"],
     )
+    jhub_domain = os.environ.get('JUPYTERHUB_DOMAIN')
+    jlab_urlprefix = os.environ.get('JUPYTERHUB_SERVICE_PREFIX')
+    if jhub_domain and jlab_urlprefix:
+        url = "{protocol}://".format(
+                protocol="https" if nb_server["secure"] else "http"
+            ) + sub(r'/+', '/', '/'.join([
+                jhub_domain,
+                jlab_urlprefix,
+                'matlab',
+            ]))

     # Fetch JupyterHub API token for HTTP request authentication
     # incase the jupyter server is started by JupyterHub.
```

But it expects to `JUPYTERHUB_DOMAIN` and `JUPYTERHUB_SERVICE_PREFIX` to be set which is special to our setup.

**Comment by prabhakk-mw** [comment]
@jhgoebbert please let us know if this didn't resolve the issue and we will be happy to reopen the issue. Thanks.

**Comment by jhgoebbert** [comment]
Sorry, I was too busy with a conference and exhibition last month. I have the testing still on my list.
