### ISSUE TITLE
Unable to interact with Matlab in browser

### ISSUE THREAD

**Issue by AndrewHerzing** [mathworks/jupyter-matlab-proxy#66]
OS: Ubuntu 20.04.6
Matlab: R2021b
jupyterlab: 3.6.3
jupyter_server: 1.23.4
jupyter-matlab-proxy: 0.7.1
matlab-proxy: 0.7.7

I can successfully open Matlab in the browser from Jupyter.  If I press enter, a new >>> terminal prompt is created.  However, I I try to enter an actual command the program freezes and nothing ever happens again:

![image](https://github.com/mathworks/jupyter-matlab-proxy/assets/15435952/358da740-13ea-45fc-b1b9-ce51298516fd)

I am accessing the Ubuntu machine remotely using ssh port forwarding and I am starting Jupyter with the --port=XXXX command.  All other non-Matlab Jupyter functionality is working.

**Comment by AndrewHerzing** [comment]
I was able to fix this issue by upgrading to R2023b.  I am not sure why or how this fixed the problem but it seems to be working now.

**Comment by prabhakk-mw** [comment]
That's good to hear! 

We've been attempting to reproduce the stall at our end with the specified configuration with no success. 

Now that you have 23b working, could you try reinstalling 21b or other releases and verifying that they work for you as well?
