### ISSUE TITLE
MATLAB Kernel Error: Invalid argument name 'regionArray'.

### ISSUE THREAD

**Issue by yanndebray** [mathworks/jupyter-matlab-proxy#67]
When updating to MATLAB 23b, I now get the following error when I start the MATLAB kernel for Jupyter (the web desktop works fine):
![image](https://github.com/mathworks/jupyter-matlab-proxy/assets/128002745/cbbed35f-ab60-41fc-aeaf-e8985cd50b29)

**Comment by yanndebray** [comment]
Ok I solved it...
I was on jupyter-matlab-proxy version 0.6.0
I updated to the latest (0.7.1), and it worked:
`pip install -U jupyter-matlab-proxy`

**Comment by rishabhdutta** [comment]
Same issue when running on 'conda environment' with python version 3.6-3.7. Use conda environment with python version >3.9.
