### ISSUE TITLE
Simulink Integration

### ISSUE THREAD

**Issue by volkherscholz** [mathworks/jupyter-matlab-proxy#7]
Great stuff, works very nicely, thanks.
Any plans to integrate Simulink as well? Would be highly appreciated.

**Comment by prabhakk-mw** [comment]
Hi @volkherscholz 
Thank you for trying the integration. We are happy to hear that its working out well for you.
Simulink integration is not being planned at this time for integration with Jupyter.
Your request for it has been recorded and it will help us prioritize its development.

In the mean time, have you tried MATLAB Online?
Simulink integration is available in [MATLAB Online](https://in.mathworks.com/products/matlab-online.html)

**Comment by prabhakk-mw** [comment]
Hi @volkherscholz 

Simulink Online is now available for use with MATLAB R2024b onwards on Linux platforms.
Check out [matlab-proxy v0.25.0](https://github.com/mathworks/matlab-proxy/releases/tag/v0.25.0) !
