### ISSUE TITLE
%%file magic broken

### ISSUE THREAD

**Issue by benkay86** [mathworks/jupyter-matlab-proxy#71]
There seems to be an issue with writing functions in Jupyter notebooks.  I have the following cell:

```
%%file hello.m

function hello()
    disp("Hello world!");
end
```

And I get:

```
Function definition are not supported in this context. Functions can only be created as local or nested functions in code files.

Error in jupyter.execute (line 51)
resp = jsondecode(matlab.internal.editor.evaluateSynchronousRequest(request));

Error in processJupyterKernelRequest (line 54)
            output = jupyter.execute(code, kernelId);

Error in connector.internal.fevalMatlab

Error in connector.internal.fevalJSON
```

Running jupyterlab 4.0.6, Matlab R2021a (9.10.0.1602886), and jupyter-matlab-proxy 0.7.2.

**Comment by rashedmyt** [comment]
Hi @benkay86

Thank you for trying out MATLAB Integration for Jupyter.

Currently, MATLAB Kernel does not support magics which are provided by IPython
and Metakernel. Hence, the line `%%file hello.m` will be treated as a comment in
MATLAB language.

Also, support for functions within a cell is only valid if it is also being used
in the same cell. For example
```
hello()

function hello()
    disp("Hello world!");
end
```
Currently, MATLAB Kernel does not support cross-cell function definition and usage.
If you are interested in this feature, please subscribe to https://github.com/mathworks/jupyter-matlab-proxy/issues/65
to get notified with related updates.

Hope this answers your query.

**Comment by benkay86** [comment]
Ah, my mistake.  The [documentation](https://am111.readthedocs.io/en/latest/jmatlab_use.html#User-defined-functions) I was following was actually for an older, not-official Jupyter-Matlab integration.
