### ISSUE TITLE
Link the kernel to a specific version of matlab

### ISSUE THREAD

**Issue by fandycheng** [mathworks/jupyter-matlab-proxy#74]
Dear Developers,

I'm currently using jupyter-matlab-proxy on my remote server to run matlab. But there are several version of matlab (e.g., matlab2016, matlab2019a, etc.). Is there anyway to specify the path for the my desired matlab version to run the kernel? Any help is appreciated. 

Cheers,
Franklin

**Comment by krisctl** [comment]
Dear @fandycheng,

Thank you for using `jupyter-matlab-proxy`!

`jupyter-matlab-proxy` uses another of our package `matlab-proxy` to manage the selection of desired MATLAB. You can make use of `MWI_CUSTOM_MATLAB_ROOT` environment variable to point the MATLAB root to a location of your choice before starting `jupyter-matlab-proxy`. Documentation on how to do that can be found [here](https://github.com/mathworks/matlab-proxy/blob/main/Advanced-Usage.md). In a Linux environment, it would look similar to:

```bash
export MWI_CUSTOM_MATLAB_ROOT=/usr/local/MATLAB/R2023a
jupyter lab
```

Hope that helps!

**Comment by prabhakk-mw** [comment]
Hi @fandycheng 

Thank you for your response.

Could you tell us a little bit more about  the executable`matlab2019a`? 
How was it created? 
What does it contain? Is it a script?

Our assumption behind suggesting the `which matlab2019a | xargs readlink -f` was that `matlab2019a` was a SYMLINK.

But given that the result is again pointing to `/disk/local_x86_64/bin`, it makes me believe that perhaps `matlab2019a` is not a symlink, and is in fact a script that somehow knows how to start MATLAB 2019a.

Please note that `MWI_CUSTOM_MATLAB_ROOT` needs to point to the folder in which the `VersionInfo.xml` file is present for a given release of MATLAB. 

Can you figure out where that would be?
