### ISSUE TITLE
Adding matlab kernel to jupyter without `xvfb`

### ISSUE THREAD

**Issue by HappySpring** [mathworks/jupyter-matlab-proxy#75]
I am currently running lots of matlab scripts on a HPC where `Xvfb` is prohibited. In this situation, it would be beneficial to connect matlab kernel to Jupyter without matlab-like GUI and the dependency of `Xvfb`.  

I installed `jupyter-matlab-proxy` on the HPC. Not surprisingly, the matlab-like GUI does not work. Besides, the matlab kernel cannot be connected from either a Jupyter notebook or a console without `Xvfb`. Is there a way to integrate matlab kernel to Jupyter using `jupyter-matlab-proxy` without `Xvfb`?

By the way, the matlab-like GUI introduced by `jupyter-matlab-proxy` is quite impressive. Thank you for your work and I hope I would be able to use it on a HPC in future.

**Comment by prabhakk-mw** [comment]
@HappySpring 

XVFB is required on unix systems when a display is not connected for us to capture the graphical outputs from commands like PLOT etc.

So, I don't think its possible to do away with the need for XVFB.
However, we will dig deeper to verify this. 

That said, does your typical use case require graphics?
Would you be happy with these HPC jobs returning only TEXT outputs from your calls to the kernel?

**Comment by HappySpring** [comment]
@prabhakk-mw 

Most of my scripts on HPC are written for preparing files for other applications and regular analysis of some outputs. Graphics are not necessary for me.

**Comment by diningPhilosopher64** [comment]
@HappySpring, the `matlab-proxy` package (which the `jupyter-matlab-proxy` package depends on) has been upgraded to warn instead of erroring out when `Xvfb` is missing.

You can upgrade it to the latest version (`v0.11.0`) as follows: 
```bash
$ python -m pip install --upgrade matlab-proxy
``` 
 

Thank you for using MATLAB Integration for Jupyter!

**Comment by HappySpring** [comment]
@diningPhilosopher64, that helps a lot. Thank you for your work, especially during the holiday season. The `jupyter-matlab-proxy` make things much easier to write, debug and run matlab scripts on servers.
