### ISSUE TITLE
Exception calling matlab error on flush on opening project

### ISSUE THREAD

**Issue by rsp34** [mathworks/jupyter-matlab-proxy#76]
Using a startup file so jupyter notebooks use a MATLAB project.

Project activation seems to work but get errors in the dialog "Exception calling matlab error on flush". 

Example of failing command:

`function success = check_python_installation()
% Check Python installations for version 3.10 to ensure compatibility with the codebase.
%
% Syntax:
%     success = check_python_installation();
%
% Description:
%     This function checks if Python 3.10 is installed and sets it as the active Python version using the pyenv function.
%     If Python is not installed or the installed version is not 3.10, an error or warning message is displayed.
%
% Outputs:
%     success: A logical value indicating whether the Python installation check was successful.
%
% Other m-files required: none
% Subfunctions: none
% MAT-files required: none

python_environment = pyenv;

if python_environment.Version == ""
    success = false;
    if nargout == 1
        warning("Python not installed. Please install Python 3.10");
        return;
    else
        error("Python not installed. Please install Python 3.10");
    end
elseif python_environment.Version ~= "3.10"
    try
       pyenv(Version="3.10");
    catch exception
        success = false;
        if strcmp(exception.identifier, "MATLAB:Python:Pyenv:VersionNotFound")
            msg = "Python 3.10 not installed. Please install Python 3.10";
            cause_exception = MException("MATLAB:Python:Pyenv:VersionNotFound", msg);
            exception = addCause(exception, cause_exception);
        end
        if nargout == 1
            warning(exception.message)
            return;
        else
            rethrow(exception)
        end   
    end
end

success = true;

end`

**Comment by Shushant2502** [comment]
Hi @rsp34,

Thank you for trying out MATLAB Integration for Jupyter.

According to my understanding, you are trying to open a MATLAB project in a Jupyter notebook with a startup file which runs `check_python_installation`. Though the project is getting activated successfully, you are facing an error message.

I tried to reproduce the issue at my end by following these steps -

1. Created a project called `myProject` in MATLAB.
2. Created the function `check_python_installation` and added it to the `Startup files` of `myProject`.
	
    ![Pasted image 20231214154058](https://github.com/mathworks/jupyter-matlab-proxy/assets/153797173/3209cccb-3444-4574-ac80-8a8646e6cd33)

3. Launch MATLAB Kernel in Jupyter notebook. 
4. Check if python version 3.10 is setup correctly in MATLAB by executing the command:

	```
	pyenv
	```
	![Pasted image 20231214154753](https://github.com/mathworks/jupyter-matlab-proxy/assets/153797173/87736686-cfab-4e5c-a096-996f77932df0)

4. Open the project in Jupyter notebook.

	![Pasted image 20231214154901](https://github.com/mathworks/jupyter-matlab-proxy/assets/153797173/64bce230-f5f5-4e08-86a5-740cff5d0830)

The project opened successfully without any errors. 

If this is not the correct procedure, then to better assist you in resolving this issue, kindly provide me with the following information -

1. Output of the [troubleshooting script](https://github.com/mathworks/jupyter-matlab-proxy/blob/main/troubleshooting/troubleshooting.md).
2. The MATLAB version you are using.
3. The exact reproduction steps to reproduce the error at my end.
4. Indicate the precise location where the error message appears. A screenshot of the error would greatly assist in troubleshooting the issue.
5. Is the error you are facing encountered only when the project is activated within the Jupyter notebook, or does it also occurs when you activate the project directly in MATLAB.

Looking forward to getting the above information from you.

**Comment by rsp34** [comment]
I can't reproduce the issue either... I originally saw it on two occasions.

I have updated to 2023b and all dependencies in the intervening period.

No longer a blocker. Thanks for your assistance. I will get in touch if I manage to reproduce the error.
