### ISSUE TITLE
Remove `jupyter-contrib-nbextensions` from install requirements

### ISSUE THREAD

**Issue by chen1682-ntu-edu-sg** [mathworks/jupyter-matlab-proxy#79]
From its [project description](https://github.com/ipython-contrib/jupyter_contrib_nbextensions?tab=readme-ov-file#jupyterlab):
> Due to major differences between the Jupyter Notebook and JupyterLab, the extensions in this repository will not work in JupyterLab. 

Bundling `jupyter-contrib-nbextensions` with the package breaks `jupyter-nbconvert` under JupyterLab 4. This is unacceptable. Old jupyter extensions like this should be avoided at all costs. Besides, I don't see `jupyter-contrib-nbextensions` being used in this project anywhere other than a [troubleshooting guide](https://github.com/mathworks/jupyter-matlab-proxy/blob/main/troubleshooting/troubleshooting.md) which presumably only applies to JupyterLab < 3.

Therefore, I propose that `jupyter-contrib-nbextensions` be:
- Either completely removed from the [install requirements](https://github.com/mathworks/jupyter-matlab-proxy/blob/e082bc364adcfe435e67be5a22c363cc2a09bea5/pyproject.toml#L48)
- Or made optional

**Comment by prabhakk-mw** [comment]
@chen1682-ntu-edu-sg , Thank you for reporting this issue!
We've updated our repository to remove its dependency on this package.
