### ISSUE TITLE
Open MATLAB [↗] from Jupyter opens the New Desktop

### ISSUE THREAD

**Issue by yanndebray** [mathworks/jupyter-matlab-proxy#83]
When clicking on `Open MATLAB [↗]` from Jupyter Launcher, this opens the [New Desktop](https://www.mathworks.com/matlabcentral/fileexchange/119593-new-desktop-for-matlab-beta) as a separate app locally on Windows.

**Comment by prabhakk-mw** [comment]
@yanndebray 
Please update your version of `matlab-proxy`.
A fix for this was submitted in https://github.com/mathworks/matlab-proxy/releases/tag/v0.11.0
