### ISSUE TITLE
Unable to install AddOns

### ISSUE THREAD

**Issue by yanndebray** [mathworks/jupyter-matlab-proxy#84]
`It looks like the webpage at https://127.0.0.1:31516/matlab/ui/install/addons_ui/index.html?workflowType=ADDONSINSTALL&matlabroot=C%3A%5CProgram%20Files%5CMATLAB%5CR2024a&installfolder=C%3A%5CProgramData%5CMATLAB%5CSupportPackages%5CR2024aPrerelease&contextKey=SSI_IN_MATLAB&artifactType=SUPPORTPACKAGE&height=350px&width=550px&basecode=QUANTUM&entryPoint=AO_SIDEPANEL&mre=https%3A%2F%2F127.0.0.1%3A31516%2Fmatlab%2F might be having issues, or it may have moved permanently to a new web address.`

![image](https://github.com/mathworks/jupyter-matlab-proxy/assets/128002745/e34b7a0f-b802-486a-9453-f7bcd2debf0a)

**Comment by prabhakk-mw** [comment]
@yanndebray 
Could you please try this after updating `jupyter-matlab-proxy` and `matlab-proxy` ?
This is possibly due to mathworks/matlab-proxy#29, which has been fixed recently.
