### ISSUE TITLE
Are administrator privileges required in the Windows system?

### ISSUE THREAD

**Issue by Rabbits-sys** [mathworks/jupyter-matlab-proxy#90]
In Windows, matlab-proxy-app will not be able to connect to MATLAB R2024a unless administrator privileges are granted, but will start a MATLAB process in the background that cannot be terminated with Jupyter Close.

In the diagram is the part of the log in Debug mode that is different from administrator mode when it is started without administrator privileges:

![屏幕截图 2024-05-09 152521](https://github.com/mathworks/jupyter-matlab-proxy/assets/79236841/93ef9e59-c3ba-475d-9ea5-7fd159a41ead)

**Comment by diningPhilosopher64** [comment]
Hello @Rabbits-sys ,

Thank you for trying the MATLAB Integration for Jupyter!

> In Windows, matlab-proxy-app will not be able to connect to MATLAB R2024a unless administrator privileges are granted,

Do you need to give admin privileges, when you double click the MATLAB icon or when you run `matlab`  in your command prompt ?

Do you see MATLAB starting in the background ? You can check the task manager on windows to see if the MATLAB process has started. 

Could you please provide the exact reproduction steps that is leading to the above error.

**Comment by Rabbits-sys** [comment]
First of all, I didn't need administrator privileges to open MATLAB with command `matlab` in the terminal. And after I tested this issue for several times I was shocked to find more than 10 MATLAB processes in the Task Manager. All the steps I did were as follows:
1. ```Shell $Env:MWI_LOG_LEVEL="DEBUG" ```
2. ```Shell jupyter lab ```
3. select the Matlab kernel.

At the same time, I also tested running `.\matlab-proxy-app` directly through the terminal without administrator privileges, and it showed the same error.

**Comment by krisctl** [comment]
Dear @Rabbits-sys,

This issue should be resolved by the latest versions of matlab-proxy and jupyter-matlab-proxy.

Could you please upgrade these packages using the command :

`pip install --upgrade jupyter-matlab-proxy matlab-proxy` 

and verify that the upgrade went through using commands like:

`pip list | Select-String "matlab-proxy"` in PowerShell.

Please let us know if the upgraded packages resolve this issue.

**Comment by Rabbits-sys** [comment]
> 亲爱的 ，
> 
> 此问题应由最新版本的 matlab-proxy 和 jupyter-matlab-proxy 解决。
> 
> 您能否使用以下命令升级这些软件包：
> 
> `pip install --upgrade jupyter-matlab-proxy matlab-proxy`
> 
> 并使用以下命令验证升级是否完成：
> 
> `pip list | Select-String "matlab-proxy"`在 PowerShell 中。
> 
> 如果升级后的程序包解决了此问题，请告知我们。

Very good work, permission issue has been resolved
