### ISSUE TITLE
New Desktop Beta : MATLAB kernel stuck at "Executing" when calling plot

### ISSUE THREAD

**Issue by alco1900** [mathworks/jupyter-matlab-proxy#96]
Hello, i have followed the instructions here: https://github.com/mathworks/jupyter-matlab-proxy and launched jupyter lab. 

I can see all the MATLAB options at the jupyter lab main page. 

The "Open MATLAB" works fine. 

The Notebook MATLAB Kernel and Console MATLAB Kernerl present the same issue: MATLAB code works fine until I call a plot function. For example, I have a ipynb notebook with the following MATLAB code:
```
x = 0:pi/100:2*pi
y = sin(x)
plot(x,y)

```
The session remains stuck at "Executing..." in the Jupyter Notebook and no plot is displayed. If I stop the execution (stop button in the top toolbar of the jupyter notebook) x and y are printed as output but no plot.

**Comment by prabhakk-mw** [comment]
Hi @alco1900 

Are you by any chance running the new desktop for MATLAB that's in beta? 

https://uk.mathworks.com/matlabcentral/fileexchange/119593-new-desktop-for-matlab-beta

The issue you describe sounds like something we've seen with the new desktop. 

If you are running the new desktop beta, could you please try disabling it and attempt the reproduction steps again?

**Comment by alco1900** [comment]
I have disabled new desktop on my matlab and It does work now, thanks!

**Comment by prabhakk-mw** [comment]
That's great news! 

We are working towards fixing this issue before the new desktop becomes the default. 

Closing for now, as there aren't any plans to fix this issue for the beta release.
