### ISSUE TITLE
my notebook runs matlabcode take a error

### ISSUE THREAD

**Issue by xiang2002** [mathworks/jupyter-matlab-proxy#98]
### Summary

![b283deb0f026a8849e1f3738d8a0199](https://github.com/user-attachments/assets/d56065bb-b8b3-46f9-8ecc-22478b8ec861)
like this...but:
![d1056791c9ef9e239ce02ca3d63406f](https://github.com/user-attachments/assets/70e10592-6e09-4399-a673-97c767d7002b)
my jupyter in run in a ubuntuserver and I open it in my WindowsPC.

### Browser(s) used

Chrome

### Issue found in

Others

**Comment by xiang2002** [comment]
why?

**Comment by krisctl** [comment]
Hi, @xiang2002!

Thanks for trying out jupyter-matlab-proxy. Can you please help out by letting us know the reason for closing the issue? Was there some setup issue that you were able to rectify on your end or anything else? 

Thanks and regards!

**Comment by xiang2002** [comment]
> Hi, @xiang2002!
> 
> Thanks for trying out jupyter-matlab-proxy. Can you please help out by letting us know the reason for closing the issue? Was there some setup issue that you were able to rectify on your end or anything else?
> 
> Thanks and regards!

 @krisctl Hello!

Thanks for your attention&reply.
![image](https://github.com/user-attachments/assets/ce841c77-17be-4a59-928d-2d4bcbf32da4)
There were three kernels generated in the process of using jupyter for matlab.The "MATLAB KERNEL" is invalid to run,but the others are useful.So,i just changed the kernel,haha😀

**Comment by krisctl** [comment]
Thanks for the reply, @xiang2002!

That does help us understand the situation a bunch. While I have your attention, do you mind sharing a bit more information about this issue and your environment? Some clarifying questions that I have are:

1. Is it the first time you are using `jupyter-matlab-proxy` or have used any other version of `jupyter-matlab-proxy` in the past?
2. If you have used this product in the past, was your workflow working fine earlier and was only recently failing?
3. Please share some more information about how you are running Jupyter. Is it Jupyter lab, Jupyter notebook, something else?
4. Are there any other packages that you have installed that enable MATLAB integration with Jupyter?
5. If you would be kind enough to run the troubleshooting steps mentioned [here](https://github.com/mathworks/jupyter-matlab-proxy/blob/main/troubleshooting/troubleshooting.md#run-troubleshooting-script), that would be really helpful.

Again, thanks a bunch for your time and looking forward to your reply.

Regards,
Krishan

**Comment by xiang2002** [comment]
> Thanks for the reply, @xiang2002!
> 
> That does help us understand the situation a bunch. While I have your attention, do you mind sharing a bit more information about this issue and your environment? Some clarifying questions that I have are:
> 
> 1. Is it the first time you are using `jupyter-matlab-proxy` or have used any other version of `jupyter-matlab-proxy` in the past?
> 2. If you have used this product in the past, was your workflow working fine earlier and was only recently failing?
> 3. Please share some more information about how you are running Jupyter. Is it Jupyter lab, Jupyter notebook, something else?
> 4. Are there any other packages that you have installed that enable MATLAB integration with Jupyter?
> 5. If you would be kind enough to run the troubleshooting steps mentioned [here](https://github.com/mathworks/jupyter-matlab-proxy/blob/main/troubleshooting/troubleshooting.md#run-troubleshooting-script) and share that output, that would be really helpful.
> 
> Again, thanks a bunch for your time and looking forward to your reply.
> 
> Regards, Krishan

Sorry to response so later!

Maybe I'm wrong,the kernel `matlab_kernel` created by `pip install matlab_kernel`,it seems like useless.I just choose a buggy kernel

**Comment by krisctl** [comment]
Hi @xiang2002,

It's been a while that I heard from you. I'll be closing this issue for now. Please leave a comment here with answers to my previously asked questions if you would like for me to reopen this issue.

Best regards,
Krishan
